### ISSUE TITLE
Rose-pine everything

### ISSUE THREAD

**Issue by hasancruk** [hasanhaja/dotfiles#13]
# Todo

- [ ] Update iTerm2 colors with rose pine
- [ ] Neovim
  - [ ] https://github.com/nvim-lualine/lualine.nvim
  - [ ] https://github.com/rose-pine/neovim/wiki/Plugin-configurations  
- [ ] Tmux
  - [ ] https://github.com/rose-pine/tmux
